services:
  db:
    image: postgres:latest
    networks:
      - hmpps
    container_name: organisations-db
    restart: always
    ports:
      - "${LOCAL_DB_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: organisations-db
      POSTGRES_USER: organisations
      POSTGRES_PASSWORD: organisations
      DPR_USER: dpr_user
      DPR_PASSWORD: dpr_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U organisations -d organisations-db"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hmpps
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: stdout,local
      DB_SERVER: db
      DB_NAME: organisations-db
      DB_USER: organisations
      DB_PASS: organisations
      DB_SSL_MODE: prefer
      LOCAL_DB_PORT: 5432
      DPR_USER: dpr_user
      DPR_PASSWORD: dpr_password
      SYSTEM_CLIENT_ID: ${SYSTEM_CLIENT_ID:-local-client-id}
      SYSTEM_CLIENT_SECRET: ${SYSTEM_CLIENT_SECRET:-local-client-secret}
      API_BASE_URL_HMPPS_AUTH: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
      API_BASE_URL_PRISON_REGISTER: https://prison-register-dev.hmpps.service.justice.gov.uk

networks:
  hmpps:
