version: "3"
services:
  db:
    image: postgres:latest
    networks:
        - hmpps
    container_name: organisations-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: organisations-db
      POSTGRES_USER: organisations
      POSTGRES_PASSWORD: organisations
      DPR_USER: dpr_user
      DPR_PASSWORD: dpr_password

networks:
  hmpps:
