generic-service:
  nameOverride: hmpps-organisations-api
  productId: "DPS123" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-organisations-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-organisations-api-cert

  # Used to access resources like SQS queues and SNS topics
  serviceAccountName: hmpps-organisations-api

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    DB_SSL_MODE: "verify-full"
    FEATURE_EVENTS_SNS_ENABLED: true
    FEATURE_EVENT_ORGANISATIONS_API_ORGANISATION_CREATED: true
    FEATURE_EVENT_ORGANISATIONS_API_ORGANISATION_UPDATED: true
    FEATURE_EVENT_ORGANISATIONS_API_ORGANISATION_DELETED: true
    FEATURE_EVENT_ORGANISATIONS_API_ORGANISATION_PHONE_CREATED: true
    FEATURE_EVENT_ORGANISATIONS_API_ORGANISATION_PHONE_UPDATED: true
    FEATURE_EVENT_ORGANISATIONS_API_ORGANISATION_PHONE_DELETED: true
    FEATURE_EVENT_ORGANISATIONS_API_ORGANISATION_WEB_CREATED: true
    FEATURE_EVENT_ORGANISATIONS_API_ORGANISATION_WEB_UPDATED: true
    FEATURE_EVENT_ORGANISATIONS_API_ORGANISATION_WEB_DELETED: true
    FEATURE_EVENT_ORGANISATIONS_API_ORGANISATION_EMAIL_CREATED: true
    FEATURE_EVENT_ORGANISATIONS_API_ORGANISATION_EMAIL_UPDATED: true
    FEATURE_EVENT_ORGANISATIONS_API_ORGANISATION_EMAIL_DELETED: true
    FEATURE_EVENT_ORGANISATIONS_API_ORGANISATION_ADDRESS_CREATED: true
    FEATURE_EVENT_ORGANISATIONS_API_ORGANISATION_ADDRESS_UPDATED: true
    FEATURE_EVENT_ORGANISATIONS_API_ORGANISATION_ADDRESS_DELETED: true
    FEATURE_EVENT_ORGANISATIONS_API_ORGANISATION_TYPES_UPDATED: true


  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-organisations-api-client-creds:
      SYSTEM_CLIENT_ID : "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
    hmpps-organisations-api-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    rds-postgresql-instance-output:
      DB_SERVER: "rds_instance_address"
      DB_NAME: "database_name"
      DB_USER: "database_username"
      DB_PASS: "database_password"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_DOMAINEVENTS_ARN: "topic_arn"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-organisations-api
