---
# Per environment values which override defaults in hmpps-organisations-api/values.yaml

generic-service:
  ingress:
    host: organisations-api.hmpps.service.justice.gov.uk

  env:
    API_BASE_URL_HMPPS_AUTH: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    FEATURE_EVENTS_SNS_ENABLED: false

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: warning
